/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio_13_Restaurante;
import Ejercicio_11_RegistroAlumnos.RegistroAlumnos;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Arrays;
import java.util.Date;
/**
 *
 * @author mavel
 */
public class RestauranteMiguel extends javax.swing.JFrame {
    
    reloj hilo1;
    automatico hilo2;
    DefaultListModel Ingredientes, Platillo;
    String [] datos;
    String [] datos1;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RestauranteMiguel.class.getName());

    /**
     * Creates new form RestauranteMiguel
     */
    public RestauranteMiguel() {
        initComponents();
        this.jList2.setModel(new DefaultListModel());
        this.Platillo = (DefaultListModel)jList2.getModel();
        this.jList1.setModel(new DefaultListModel());
        Ingredientes=(DefaultListModel)jList1.getModel();
        Ingredientes.addElement("Frijoles");
        Ingredientes.addElement("Tortillas");
        Ingredientes.addElement("Huevo");
        Ingredientes.addElement("Zopa arroz");
        Ingredientes.addElement("Salchicha");
        Ingredientes.addElement("Chorizo");
        Ingredientes.addElement("Papas");
        Ingredientes.addElement("Nopales");
        Ingredientes.addElement("Verdura");
        Ingredientes.addElement("Chile");
        hilo1 = new reloj();
        hilo1.start();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        bntanadir = new javax.swing.JButton();
        btnanadirtodo = new javax.swing.JButton();
        bntquitar = new javax.swing.JButton();
        bntquitartodo = new javax.swing.JButton();
        bntespecial = new javax.swing.JButton();
        btnordenar = new javax.swing.JButton();
        btnautomatico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arme tu platillo usted mismo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre del platillo: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 370, -1));

        btnok.setText("OK");
        btnok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnokMouseClicked(evt);
            }
        });
        btnok.addActionListener(this::btnokActionPerformed);
        jPanel2.add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 600, 90));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("RESTAURANT EL COME CUANDO HAY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 630, 50));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 110));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, 110));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Platillo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Ingredientes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bebida", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jRadioButton2.setText("Agua de sabor");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jRadioButton3.setText("Refresco");
        jPanel3.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jRadioButton4.setText("Chela");
        jRadioButton4.addActionListener(this::jRadioButton4ActionPerformed);
        jPanel3.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 160, 130));

        bntanadir.setText("Añadir");
        bntanadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntanadirMouseClicked(evt);
            }
        });
        bntanadir.addActionListener(this::bntanadirActionPerformed);
        jPanel1.add(bntanadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 110, -1));

        btnanadirtodo.setText("Añadir todo");
        btnanadirtodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnanadirtodoMouseClicked(evt);
            }
        });
        jPanel1.add(btnanadirtodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, -1));

        bntquitar.setText("Quitar");
        bntquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntquitarMouseClicked(evt);
            }
        });
        jPanel1.add(bntquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 110, -1));

        bntquitartodo.setText("Quitar todo");
        bntquitartodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntquitartodoMouseClicked(evt);
            }
        });
        bntquitartodo.addActionListener(this::bntquitartodoActionPerformed);
        jPanel1.add(bntquitartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 110, -1));

        bntespecial.setText("Especial");
        bntespecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntespecialMouseClicked(evt);
            }
        });
        jPanel1.add(bntespecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 110, -1));

        btnordenar.setText("Ordenar");
        btnordenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnordenarMouseClicked(evt);
            }
        });
        jPanel1.add(btnordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 90, -1));

        btnautomatico.setText("Automatico");
        btnautomatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnautomaticoMouseClicked(evt);
            }
        });
        jPanel1.add(btnautomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel6.setText("Hora: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, -1));

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void bntquitartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntquitartodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntquitartodoActionPerformed

    private void bntanadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntanadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntanadirActionPerformed

    private void bntanadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntanadirMouseClicked
       int i = jList1.getSelectedIndex();
       Platillo.addElement(Ingredientes.getElementAt(i));
       this.Ingredientes.remove(i);
    }//GEN-LAST:event_bntanadirMouseClicked

    private void bntquitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntquitarMouseClicked
       int i = jList2.getSelectedIndex();
       Ingredientes.addElement(Platillo.getElementAt(i));
       this.Platillo.remove(i);
    }//GEN-LAST:event_bntquitarMouseClicked

    private void btnanadirtodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanadirtodoMouseClicked
       int i = Ingredientes.getSize();
       
        for (int j = 0; j < i; j++) {
           Platillo.addElement(Ingredientes.getElementAt(j));
           
        }
        Ingredientes.removeAllElements();
    }//GEN-LAST:event_btnanadirtodoMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int i=Ingredientes.getSize();
        if (i<0) {
            System.out.println("Lista vacia");
        }
        
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        int i=Platillo.getSize();
        if (i<0) {
            System.out.println("Lista vacia");
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void bntquitartodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntquitartodoMouseClicked
        int i = Platillo.getSize();

        for (int j = 0; j < i ; j++) {
            Ingredientes.addElement(Platillo.getElementAt(j));

        }
        Platillo.removeAllElements();
    }//GEN-LAST:event_bntquitartodoMouseClicked

    private void bntespecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntespecialMouseClicked
        String especial=JOptionPane.showInputDialog("Ingresa ingrediente: ");
        Ingredientes.addElement(especial);
    }//GEN-LAST:event_bntespecialMouseClicked

    private void btnordenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnordenarMouseClicked

        int i = Ingredientes.getSize();

        datos = new String[i];

        for (int j = 0; j < i; j++) {
            //Platillo.addElement(Ingredientes.getElementAt(j));
            datos[j] = Ingredientes.getElementAt(j).toString();
        }
        Ingredientes.removeAllElements();
        Arrays.sort(datos);//para ordenr arreglos de caulquier tipo
        
        for (int j = 0; j < i; j++) {
            
            Ingredientes.addElement(datos[j]);
           
        }


    }//GEN-LAST:event_btnordenarMouseClicked

    private void btnautomaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnautomaticoMouseClicked
        
        {

        }
    }//GEN-LAST:event_btnautomaticoMouseClicked

    private void btnokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokMouseClicked
        Salida nv = new Salida();
        String xx=this.jTextField1.getText();
        nv.recibirdatos(xx);
        
        this.setVisible(false);
        
         int t = Platillo.getSize();
         datos1 = new String[t];
        
        for (int j = 0; j < t; j++) {
            datos1[j] = Platillo.getElementAt(j).toString();
        }
        
        nv.recibirplatillo(datos1, t);
        
        nv.setVisible(true);
        this.setVisible(false);
         
    }//GEN-LAST:event_btnokMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RestauranteMiguel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntanadir;
    private javax.swing.JButton bntespecial;
    private javax.swing.JButton bntquitar;
    private javax.swing.JButton bntquitartodo;
    private javax.swing.JButton btnanadirtodo;
    private javax.swing.JButton btnautomatico;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnordenar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    class automatico extends Thread {

        @Override
        public void run() {

            int i = Ingredientes.getSize();
            int j = Platillo.getSize();

            if (i > j) {
                for (int x = 0; x < i; x++) {
                    Platillo.addElement(Ingredientes.getElementAt(0));
                    Ingredientes.removeElementAt(0);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        System.getLogger(RestauranteMiguel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }

                }
            }else{
                for (int x = 0; x < j; x++) {
                    Ingredientes.addElement(Platillo.getElementAt(0));
                    Platillo.removeElementAt(0);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        System.getLogger(RestauranteMiguel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }

                }
            }

        }
    }
    
    class reloj extends Thread {

        @Override
        public void run() {
            while (true) {
                Date fecha = new Date();
                String formato = "hh:mm:ss";
                String formato2 = "dd-MM-yyyy";
                SimpleDateFormat ff = new SimpleDateFormat(formato2);
                SimpleDateFormat fh = new SimpleDateFormat(formato);
                jLabel7.setText(ff.format(fecha));
                jLabel8.setText(fh.format(fecha));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.getLogger(RegistroAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        }
    }
}
