/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio_18_Empresa;

import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author mavel
 */
public class EmpleadosConsulta extends javax.swing.JFrame {
    conexionmysql cm= new conexionmysql(); 
    Empleado e;
    Connection c;
    Statement t;
    ResultSet r;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmpleadosConsulta.class.getName());

    /**
     * Creates new form EmpleadosConsulta
     */
    public EmpleadosConsulta() throws SQLException {
        initComponents();
        cm.Conexion("empresax");
        c=cm.getConnection();
        mostrarDatos();
        setLocationRelativeTo(null);
    }
    
    public void mostrarDatos() throws SQLException{
        t = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String sql="Select * from empleados";
        r= t.executeQuery(sql);
        r.first();
        this.jTextField1.setText(r.getString(1));
        this.jTextField2.setText(r.getString(2));
        this.jTextField3.setText(r.getString(3));
        this.jTextField4.setText(r.getString(4));
        this.jTextField5.setText(r.getString(5));
        
    }
    
    public void mostrarDatos2() throws SQLException{
        this.jTextField1.setText(r.getString(1));
        this.jTextField2.setText(r.getString(2));
        this.jTextField3.setText(r.getString(3));
        this.jTextField4.setText(r.getString(4));
        this.jTextField5.setText(r.getString(5));
    }

    public void Limpiar(){
        this.jTextField1.setText(null);
        this.jTextField2.setText(null);
        this.jTextField3.setText(null);
        this.jTextField4.setText(null);
        this.jTextField5.setText(null);
        this.jTextField1.requestFocus();
        
    }
    
   
    
    public void Buscar(String id) throws SQLException{
        String sql = "Select * from empleados where id_empleado= '" + id + "'";
        t = cm.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        r = t.executeQuery(sql);
        r.first();
        this.jTextField1.setText(r.getString(1));
        this.jTextField2.setText(r.getString(2));
        this.jTextField3.setText(r.getString(3));
        this.jTextField4.setText(r.getString(4));
        this.jTextField5.setText(r.getString(5));
 
    }
    
     public void InsertarE(){
        String id_empleado, nombre;
        float sueldo;
        int edad, antiguedad;
        id_empleado=jTextField1.getText();
        nombre = jTextField2.getText();
        edad= Integer.parseInt(this.jTextField3.getText());
        sueldo = Float.parseFloat(this.jTextField4.getText());
        antiguedad= Integer.parseInt(this.jTextField5.getText());
        e = new Empleado(id_empleado, nombre, edad,sueldo,antiguedad);
    }
     
    public void InsertarEnBase(Empleado e) throws SQLException{
        String sql ="Insert into empleados(id_empleado, nombre, edad, sueldo, antiguedad)" 
        + " values ('" + e.getId_empleado() + "','"
        + e.getNombre() + "',"
        + e.getEdad() + ", "
        + e.getSueldo() + ", "
        + e.getAntiguedad() + ")";
       
        t=cm.getConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        t.executeUpdate(sql);
       
    }
    
    public void DesactivarBotones(){
        btninsertar.setEnabled(false);
        btnbuscar.setEnabled(false);
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnprimero = new javax.swing.JButton();
        btnanterior = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        btnultimo = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("C o n s u l t a  d e  E m p l e a d o ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 280, 40));

        jLabel2.setText("ID_EMPLEADO: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 56, -1, 40));

        jLabel3.setText("Antiguedad: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 100, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 290, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 290, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 290, 30));

        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 290, 30));

        jLabel4.setText("Nombre: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 80, 30));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 290, 30));

        jLabel5.setText("Edad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 70, 30));

        jLabel6.setText("Sueldo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 70, 30));

        btnprimero.setText("Primero");
        btnprimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprimeroMouseClicked(evt);
            }
        });
        btnprimero.addActionListener(this::btnprimeroActionPerformed);
        jPanel1.add(btnprimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        btnanterior.setText("Anterior");
        btnanterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnanteriorMouseClicked(evt);
            }
        });
        btnanterior.addActionListener(this::btnanteriorActionPerformed);
        jPanel1.add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        btnsiguiente.setText("Siguiente");
        btnsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsiguienteMouseClicked(evt);
            }
        });
        btnsiguiente.addActionListener(this::btnsiguienteActionPerformed);
        jPanel1.add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        btnultimo.setText("Ultimo");
        btnultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnultimoMouseClicked(evt);
            }
        });
        btnultimo.addActionListener(this::btnultimoActionPerformed);
        jPanel1.add(btnultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoMouseClicked(evt);
            }
        });
        btnnuevo.addActionListener(this::btnnuevoActionPerformed);
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        btninsertar.setText("Insertar");
        btninsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninsertarMouseClicked(evt);
            }
        });
        btninsertar.addActionListener(this::btninsertarActionPerformed);
        jPanel1.add(btninsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        btnbuscar.addActionListener(this::btnbuscarActionPerformed);
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprimeroActionPerformed

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
         
    }//GEN-LAST:event_btnbuscarMouseClicked

    private void btnnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMouseClicked
       
    }//GEN-LAST:event_btnnuevoMouseClicked

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
         try {
            DesactivarBotones();
            if (r.next()) {
                mostrarDatos2();
                btnanterior.setEnabled(true);
            }else{
                r.previous();
            }
        } catch (SQLException ex) {
            System.getLogger(EmpleadosConsulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btninsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertarMouseClicked
        
        
    }//GEN-LAST:event_btninsertarMouseClicked

    private void btnprimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprimeroMouseClicked
       try {
            DesactivarBotones();
            if (r.first()) {
                mostrarDatos2();
                btnanterior.setEnabled(false);
                
            }
        } catch (SQLException ex) {
            System.getLogger(EmpleadosConsulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } 
    }//GEN-LAST:event_btnprimeroMouseClicked

    private void btnanteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanteriorMouseClicked
        
    }//GEN-LAST:event_btnanteriorMouseClicked

    private void btnsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsiguienteMouseClicked
       
        
    }//GEN-LAST:event_btnsiguienteMouseClicked

    private void btnultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnultimoMouseClicked
        
        
    }//GEN-LAST:event_btnultimoMouseClicked

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        try {
            String id_empleado = jTextField1.getText();
            String nombre = jTextField2.getText();
            String edad = jTextField3.getText();
            String sueldo = jTextField4.getText();
            String antiguedad = jTextField5.getText();
            
            if (id_empleado.isEmpty()|| nombre.isEmpty()|| edad.isEmpty()|| sueldo.isEmpty()|| antiguedad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Checa los datos");
            }else{
            InsertarE();
            InsertarEnBase(e);
            JOptionPane.showMessageDialog(this,"Empleado insertado correctamente");
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            }
           
            
            
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error en ingresar datos");
            
        }
    }//GEN-LAST:event_btninsertarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {
            String id = jTextField1.getText();
            
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Escribe un id");
                return;
            }
            
            Buscar(id);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar al empleado");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        Limpiar();
        JOptionPane.showMessageDialog(this, "Campos limpiados");
        btninsertar.setEnabled(true);
        btnbuscar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultimoActionPerformed
        try {
            DesactivarBotones();
            if (r.last()) {
               mostrarDatos2(); 
               btnsiguiente.setEnabled(false);
            }
            
        } catch (SQLException ex) {
            System.getLogger(EmpleadosConsulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnultimoActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
        try {
            DesactivarBotones();
            if(r.previous()){
                mostrarDatos2();
                
            }
        } catch (SQLException ex) {
            System.getLogger(EmpleadosConsulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new EmpleadosConsulta().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(EmpleadosConsulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnprimero;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
