/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import modelo.Alumno;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mavel
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    
    /**
     * Creates new form VentanaPrincipal
     */
    
    //Declaramos nuestra lista alumnos, ya que no sabemos cuantos alumnos vamos a registrar
    //Almacenamos objetos de tipo Alumno
    ArrayList<Alumno> alumnos = new ArrayList<>();
    
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);//Para que la ventana salga centrada. 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCalificacion = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();
        btnlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("R E G I S T R O  A L U M N O S");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        lblMatricula.setText("Matricula: ");
        jPanel1.add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 20));

        lblNombre.setText("Nombre: ");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 40));

        lblEdad.setText("Edad: ");
        jPanel1.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 110, 60, 40));

        lblCalificacion.setText("Calificación final: ");
        jPanel1.add(lblCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 30));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        txtCalificacion.addActionListener(this::txtCalificacionActionPerformed);
        jPanel1.add(txtCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 230, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Edad", "Calificación final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegistro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 500, 200));

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(this::btnlimpiarActionPerformed);
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalificacionActionPerformed

    //Nuestro boton agregar
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       String matricula, nombre; //Variables para texto
       int edad;  //Variable para la edad
       double calificacion; //Variable para la calificacion
       
       matricula = txtMatricula.getText(); //Obtenemos el valor de la caja de texto txtMatricula
       nombre = txtNombre.getText(); //Obtenemos el valor de la caja de texto txtNombre
       edad = Integer.parseInt(txtEdad.getText()); //Obtenemos el valor de la caja de texto txtEdad
       calificacion = Double.parseDouble(txtCalificacion.getText()); //Obtenemos el valor de la caja de texto txtCalificacion
       
       Alumno alumno = new Alumno(matricula, nombre, edad, calificacion); //Creamos un objeto Alumno con los datos capturados en el formulario
       alumnos.add(alumno); //Agregamos el objeto Alumno a la lista de alumnos
       
       DefaultTableModel modelo = (DefaultTableModel) tblRegistro.getModel(); //Configuramos nuestra tabla
       
       
       //Aquí se hace el llenado de la tabla
       modelo.addRow(new Object[]{
       alumno.getIdAlumno(),
       alumno.getNombreAlumno(),
       alumno.getEdadAlumno(),
       alumno.getCalificacionFinal()
       });
       
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    //Configuramos el boton limpiar para que borre los datos de las cajas de texto
    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
    txtMatricula.setText(null);
    txtNombre.setText(null);
    txtEdad.setText(null);
    txtCalificacion.setText(null);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblRegistro;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
