/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio_9_Peliculas;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.awt.GridLayout;

/**
 *
 * @author mavel
 */
public class Cartelera extends javax.swing.JFrame {

    ActionListener escucha = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            pe(e);
        }
    };

    JButton boton; //crear la coleccion de botones
    Image foto;
    Pelicula[] p = new Pelicula[5];

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cartelera.class.getName());

    /**
     * Creates new form Cartelera
     */
    public Cartelera() {
        initComponents();
        jPanel2.setLayout(new GridLayout(5, 1));
         this.setLocationRelativeTo(null);
        for (int i = 1; i <= 5; i++) {
            boton = new JButton();
            boton.setName(String.valueOf(i));
            boton.addActionListener(escucha);//aplica el escucha ActionListener
            boton.setVisible(true);

            //añadir imagen
            foto = Toolkit.getDefaultToolkit().getImage("./src/Ejercicio_9_Peliculas/Imagenes/" + i + ".png");
            boton.setIcon(new ImageIcon(foto.getScaledInstance(80, 50, 0)));
            jPanel2.add(boton);
        }
        Llenar();
    }
    public void pe(ActionEvent e){
        JButton  miguel = (JButton) e.getSource();
        String n  = miguel.getName();
        int i = Integer.parseInt(n);
        foto = Toolkit.getDefaultToolkit().getImage("./src/Ejercicio_9_Peliculas/Imagenes/" + n + ".png");
        jLabel1.setIcon(new ImageIcon(foto.getScaledInstance(420, 250, 0)));
        this.jTextArea1.setText(p[i-1].mostrarDatos());
        
    }
    
    public void Llenar() {
    p[0] = new Pelicula(
        "Guerra Civil",
        "Alex Garland",
        "En un futuro cercano, Estados Unidos se encuentra dividido por una guerra interna. Un grupo de periodistas viaja por el país para documentar el conflicto y sobrevivir al caos."
    );

    p[1] = new Pelicula(
        "War Machine",
        "Netflix",
        "Un general estadounidense lidera una complicada operación militar mientras enfrenta problemas políticos, estratégicos y personales durante la guerra."
    );

    p[2] = new Pelicula(
        "Hackers",
        "Iain Softley",
        "Un grupo de jóvenes hackers descubre una conspiración informática y debe usar sus habilidades para demostrar su inocencia y detener una amenaza digital."
    );

    p[3] = new Pelicula(
        "Incoming",
        "Netflix",
        "Un grupo de estudiantes de primer año asiste a una fiesta que cambia por completo su experiencia escolar, enfrentándose a situaciones inesperadas y cómicas."
    );

    p[4] = new Pelicula(
        "Spirit: Stallion of the Cimarron",
        "DreamWorks",
        "Spirit, un caballo salvaje, lucha por conservar su libertad mientras vive aventuras en el viejo oeste y forma un vínculo con un joven indígena."
    );
}
    
    
    /**ss
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 400));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 470, 100));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 470, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cartelera().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
