/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.mysql.cj.xdevapi.Result;
import javax.swing.table.AbstractTableModel;
import datos.conexionmysql;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import modelo.Alumno;

/**
 *
 * @author mavel
 */
public class InterfazAlumnos extends javax.swing.JFrame {
    reloj hilo1;

    DefaultTableModel miTabla;
    conexionmysql cm;
    Connection c;
    Statement t;
    ResultSet r;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazAlumnos.class.getName());

    /**
     * Creates new form InterfazAlumnos
     */
    public InterfazAlumnos() throws SQLException {
        initComponents();
        hilo1 = new reloj();
        hilo1.start();
        this.setLocationRelativeTo(null);
        configurarTabla();
        cm = new conexionmysql();
        cm.Conexion("proyecto_ldsm303");
        llenarTabla();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public void mostrarDatos() throws SQLException {
        txtmatricula.setText(r.getString(1));
        txtnombre.setText(r.getString(2));
        cmbgrupo.setSelectedItem(r.getString(3));

    }

    public void configurarTabla() {
        miTabla = new DefaultTableModel();
        miTabla.addColumn("MATRICULA");
        miTabla.addColumn("NOMBRE");
        miTabla.addColumn("GRUPO");
        this.MiTablaAlumnos.setModel(miTabla);
    }

    public void llenarTabla() throws SQLException {
        c = cm.getConnection(); //conexion
        t = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE); //mensajero
        String sql = "SELECT * FROM alumno"; // consulta
        r = t.executeQuery(sql); // recibe la informacion
        r.beforeFirst(); //preparar la lectura
        miTabla.setRowCount(0);

        while (r.next()) {

            Object[] datos = {r.getString(1), r.getString(2), r.getString(3)};
            miTabla.addRow(datos);
        }

    }

    public void registrarAlumno(Alumno alum) throws SQLException {

        t = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String sql = "INSERT INTO ALUMNO (matricula, nombre, grupo) values('"
                + alum.getMatricula() + "','" + alum.getNombre() + "','" + alum.getGrupo() + "')";
        t.executeUpdate(sql);

    }

    public void selectTabla() throws SQLException {
        int i = this.MiTablaAlumnos.getSelectedRow();
        String x = (String) miTabla.getValueAt(i, 0);
        String sql = "SELECT * FROM alumno WHERE matricula='" + x + "'";
        t = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        r = t.executeQuery(sql);
        r.first();
        mostrarDatos();
    }

    public void eliminarAlumno() throws SQLException {
        String matricula = txtmatricula.getText();
        t = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String sql = "DELETE FROM alumno WHERE matricula ='" + matricula + "'";
        t.executeUpdate(sql);

    }
    
    public void editarAlumno(Alumno alum) throws SQLException{
        t = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String sql = "UPDATE alumno " +
                    "SET matricula='"+ alum.getMatricula() + "', " + "nombre='" + alum.getNombre() + "', " + "grupo='" + alum.getGrupo() + "' " +
                    "WHERE matricula='" + alum.getMatricula() + "'";
        t.executeUpdate(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnmostrartodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiTablaAlumnos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cmbgrupo = new javax.swing.JComboBox<>();
        lblFechaActual = new javax.swing.JLabel();
        lblHoraActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UTL A LA VANGUARDIA EN IoT - REGISTRO DE ALUMNOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 10, 580, -1));

        jLabel2.setText("Nombre: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 20));

        jLabel3.setText("Matricula: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 20));

        txtmatricula.addActionListener(this::txtmatriculaActionPerformed);
        jPanel1.add(txtmatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 320, -1));

        txtnombre.addActionListener(this::txtnombreActionPerformed);
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 320, -1));

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(this::btnnuevoActionPerformed);
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 90, -1));

        btnregistrar.setText("REGISTRAR");
        btnregistrar.addActionListener(this::btnregistrarActionPerformed);
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(this::btneliminarActionPerformed);
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 90, -1));

        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(this::btnactualizarActionPerformed);
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, -1));

        btnmostrartodo.setText("MOSTRAR TODO");
        btnmostrartodo.addActionListener(this::btnmostrartodoActionPerformed);
        jPanel1.add(btnmostrartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        MiTablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MiTablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiTablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MiTablaAlumnos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 490, 190));

        jLabel4.setText("GRUPO: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        cmbgrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LDSM301", "LDSM302", "LDSM303", "LDSM304" }));
        jPanel1.add(cmbgrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        lblFechaActual.setText("Fecha:");
        jPanel1.add(lblFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 20));

        lblHoraActual.setText("Hora:");
        jPanel1.add(lblHoraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 110, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatriculaActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (txtmatricula.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un alumno");
            return;
        }
        try {
            eliminarAlumno();
            llenarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno eliminado");
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar el alumno");
            System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        String matricula, nombre, grupo;
        matricula = txtmatricula.getText();
        nombre = txtnombre.getText();
        grupo = (String) cmbgrupo.getSelectedItem();

        if (matricula.isEmpty() || nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Completa la matricula y el nombre");
            return;
        }

        Alumno registro = new Alumno(matricula, nombre, grupo);

        try {
            registrarAlumno(registro);
            llenarTabla();
            txtmatricula.setText(null);
            txtnombre.setText(null);
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno registrado");
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el alumno");
            System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        txtmatricula.setText(null);
        txtnombre.setText(null);

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        String matricula, nombre, grupo;
        matricula = txtmatricula.getText();
        nombre = txtnombre.getText();
        grupo = (String) cmbgrupo.getSelectedItem();

        if (matricula.isEmpty() || nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Completa la matricula y el nombre");
            return;
        }
        
        Alumno actualizar = new Alumno(matricula, nombre, grupo);
        
        try {
            editarAlumno(actualizar);
            llenarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno actualizado");
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo actualizar el alumno");
            System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void MiTablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiTablaAlumnosMouseClicked
        try {
            selectTabla();
        } catch (SQLException ex) {
            System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_MiTablaAlumnosMouseClicked

    private void btnmostrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrartodoActionPerformed
        try {
            llenarTabla();
            txtmatricula.setText(null);
            txtnombre.setText(null);       
        } catch (SQLException ex) {
            System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnmostrartodoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new InterfazAlumnos().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MiTablaAlumnos;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmostrartodo;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> cmbgrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblHoraActual;
    private javax.swing.JTextField txtmatricula;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    class reloj extends Thread {
        public void run() {
            while (true) {
                Date fecha = new Date();
                String formato = "hh:mm:ss";
                String formato2 = "dd-MM-yyyy";
                SimpleDateFormat ff = new SimpleDateFormat(formato2);
                SimpleDateFormat fh = new SimpleDateFormat(formato);
                lblFechaActual.setText("Fecha: " + ff.format(fecha));
                lblHoraActual.setText("Hora: " + fh.format(fecha));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.getLogger(InterfazAlumnos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        }
    }
}
