/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mavel
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAlumnos = new javax.swing.JButton();
        btnConferencistas = new javax.swing.JButton();
        btnConferencias = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión UTL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE GESTIÓN UTL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione una opción del menú:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 450, -1));

        btnAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlumnos.setText("Gestión de Alumnos");
        btnAlumnos.addActionListener(this::btnAlumnosActionPerformed);
        jPanel1.add(btnAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 250, 40));

        btnConferencistas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConferencistas.setText("Gestión de Conferencistas");
        btnConferencistas.addActionListener(this::btnConferencistasActionPerformed);
        jPanel1.add(btnConferencistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 250, 40));

        btnConferencias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConferencias.setText("Gestión de Conferencias");
        btnConferencias.addActionListener(this::btnConferenciasActionPerformed);
        jPanel1.add(btnConferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 250, 40));

        btnSalir.setText("Salir del Sistema");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        try {
            new InterfazAlumnos().setVisible(true);
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnConferencistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferencistasActionPerformed
        try {
            new Conferencistas().setVisible(true);
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConferencistasActionPerformed

    private void btnConferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferenciasActionPerformed
        try {
            new Conferencias().setVisible(true);
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConferenciasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnConferencias;
    private javax.swing.JButton btnConferencistas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
